export const restaurantTypes = {
    CREATE_RESTAURANT: 'CREATE_RESTAURANT',
    GET_RESTAURANTS: 'GET_RESTAURANTS',
    CURRENT_RESTAURANT: 'CURRENT_RESTAURANT',
    DELETE_RESTAURANT: 'DELETE_RESTAURANT'
}